### ISSUE TITLE
Failing Integration Tests

### ISSUE THREAD

**Issue by andrewkcorcoran** [PlatformLab/NanoLog#19]
See attached error log when running integrationTest/run.sh on Linux RHEL 7.4 with gcc 8.3.1 and python 2.7.5.

[IntegerationTestsErrors.txt](https://github.com/PlatformLab/NanoLog/files/4009316/IntegerationTestsErrors.txt)

**Comment by syang0** [comment]
Hi Andrew,

I believe the test failures you're experiencing are benign, and are due to slight differences in the build order of the integration tests. I've updated the tests so that they are more order agnostic.

Please pull the latest commit and let me know if the issues persist =)

Best Regards,
Stephen Yang

**Comment by andrewkcorcoran** [comment]
That's great thanks, the new commit fixed the issue.
