### ISSUE TITLE
sampleApplication in sample directory has segfault

### ISSUE THREAD

**Issue by wizwx** [PlatformLab/NanoLog#35]
I check out the head (4d1afc8) and then run make first in the runtime and then in the sample directory.
I then run ./sampleApplication in the sample directory, and it has segfault.
gdb indicates that the segfault happens in the compression thread.

**Comment by syang0** [comment]
Hi wizwx,

Hm... shoot, I think I know what the problem is; the short-term fix is to run `make clean-all; make` in the sample directory.

If this works, I suspect the problem is that the preprocessor version of the library was compiled, but we're trying to use it for the C++17 version of the application. I think this problem was introduced with commit 13ab4cc, and I'll need a little bit of time to think of a proper solution. But for now, let me know if the short-term solution works.

Best Regards,
Stephen Yang

**Comment by wizwx** [comment]
Thanks for the suggestion.
make clean-all and then make in the sample directory works.
If i run make libNanoLog.a in runtime and then make in sample also works.
Now I can see that you are using precompile mode for test and in doing so the library libNanoLog.a is compiled with precompile mode.
I would suggest that you compile two versions of libNanoLog.a by running make in runtime: one for precompile and one for c++17. People can choose which one to link depending on which version to use. You should also compile and run your test cases for both scenarios.

**Comment by syang0** [comment]
Hey wizwx,

I took your suggestion and now the two libraries build to separate directories  as of commit dc0efa1 =)

Best Regards,
Stephen Yang
